/****** Сценарий для команды SelectTopNRows среды SSMS  ******/
SELECT TOP 1000 [udf_type_id]
      ,[table_name]
      ,[udf_type_name]
      ,[udf_type_label]
      ,[logical_data_type]
      ,[super_flag]
      ,[udf_code_short_len]
      ,[formula]
      ,[indicator_expression]
      ,[disp_data_flag]
      ,[disp_indicator_flag]
      ,[summary_indicator_expression]
      ,[summary_method]
      ,[update_date]
      ,[update_user]
      ,[create_date]
      ,[create_user]
      ,[delete_session_id]
      ,[delete_date]
  FROM [tempPMDB].[dbo].[UDFTYPE]